# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a13fbc97cec99742a88ad518971670e4f7f3f77e077d065830edfb825d19a3329e1d5b7756018fc3f4dbb2445c1951569b69bb81416a5a6bac72dc9afec7180e

test:
  secret_key_base: a9a3ed72bbd8da391981dc72f85c34d5e217e7d7e6b728aa9bc9cfbfad940599f35204c1329bbef6c562286470efe705b895b6b80571cb8c020f1958151ec27c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
